debug: true


bot:
  prefix:        "Bot's prefix"
  token:         "Bot's Token"
  trace_loggers: "!"


style:

  colours:
      blue: 0x3775a8
      bright_green: 0x01d277
      orange: 0xe67e22
      pink: 0xcf84e0
      purple: 0x554e8d
      soft_green: 0x68c290
      soft_orange: 0xf9cb54
      soft_red: 0xcd6d6d
      white: 0xfffffe
      yellow: 0xffd241

  emojis:
    trashcan: "\U0001F5D1"


guild:

  id: 111111111111111111
  invite: "Invite to home guild."


  categories:

    admins:                         111111111111111111
    moderators:     &MODS_CATEGORY  111111111111111111
    voice:                          111111111111111111


  channels:

    # Public announcement and news channels
    announcements:                   111111111111111111

    # Stuff
    admins:         &ADMINS         111111111111111111
    admins_spam:    &ADMINS_SPAM    111111111111111111
    moderators:     &MODS           111111111111111111
    bot_commands:   &BOT_CMD        111111111111111111

    # Logs
    mod_log:        &MOD_LOG        111111111111111111
    user_log:                       111111111111111111
    message_log:    &MESSAGE_LOG    111111111111111111
    voice_log:                      111111111111111111

    # Voice
    voice_chat_0:                   111111111111111111
    voice_chat_1:                   111111111111111111
    voice_chat_afk:                 111111111111111111

    modlog_blacklist:
      - *MOD_LOG
      - *MESSAGE_LOG


  moderation_categories:
    - *MODS_CATEGORY


  moderation_channels:
    - *ADMINS
    - *ADMINS_SPAM
    - *MODS


  roles:
    owners:         &OWNERS_ROLE    111111111111111111
    admins:         &ADMINS_ROLE    111111111111111111
    moderators:     &MODS_ROLE      111111111111111111
    mod_team:       &MOD_TEAM_ROLE  111111111111111111
    regular:                        111111111111111111
    bots:                           111111111111111111


  moderation_roles:
    - *OWNERS_ROLE
    - *ADMINS_ROLE
    - *MODS_ROLE
    - *MOD_TEAM_ROLE


  staff_roles:
    - *OWNERS_ROLE
    - *ADMINS_ROLE
    - *MOD_TEAM_ROLE


redirect_output:
  delete_delay: 15
  delete_invocation: true


urls:
  # Discord API URLs
  discord_api:        &DISCORD_API "https://discordapp.com/api/v7/"
  discord_invite_api: !JOIN [*DISCORD_API, "invites"]
 
  # GitHub
  github_bot_repo:    "https://github.com/SidVeld/Incarn"
  github_bot_origin:  "https://github.com/python-discord/bot"
